# Generated by Django 3.0.4 on 2020-03-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='brand_id',
            field=models.CharField(default=None, max_length=3),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='color_id',
            field=models.CharField(default=None, max_length=3),
        ),
        migrations.AddField(
            model_name='product',
            name='prodType',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='prodType_id',
            field=models.CharField(default=None, max_length=3),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='size_id',
            field=models.CharField(default=None, max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_added',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=None),
        ),
    ]
